blah

diff --git a/usr/bin/egup-single b/usr/bin/egup-single
--- a/usr/bin/egup-single
+++ b/usr/bin/egup-single
@@ -5,29 +5,32 @@ source ember_bash_setup &> /dev/null
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 #set -x
 
+if [[ "$1" == "--offline" ]]; then
+    offline="true"
+fi
+
 cd "$1" || exit 1
 
 branch="$(git branch | grep -E "^\* " | cut -c 3-)"
 git checkout "$branch"
-set -e
-git add -A || error-notify "ERROR adding changes."
-git add -A . || error-notify "ERROR adding changes."
-set +e
+git add -A || die "ERROR adding changes."
+git add -A . || die "ERROR adding changes."
+trap - ERR
 git commit -a -m "Update Ember tree"
-set -e
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 if [[ -f .egup.hooks ]]; then
     echo "Beginning running hooks..."
     ./.egup.hooks || warn "WARNING! pre-build-hooks failed; continuing anyway."
     echo "Done running hooks."
-    set +e
+    trap - ERR
     git commit -a -m "Update Ember tree"
-    set -e
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 fi
 git show-ref -d --tags > .egup.tags || echo "(Note: Repository appears to have no tags.)"
 git add -A || error-notify "ERROR adding tag changes."
-set +e
+trap - ERR
 git commit -a -m "Update Ember tree"
-set -e
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 git pull --all || error-notify "ERROR pulling."
 git submodule update --remote || warn "ERROR updating submodules. Maybe a remote server is down?"
 if ! [[ -f .egup.nopush ]]; then
