Update Ember tree

diff --git a/usr/bin/egup-single b/usr/bin/egup-single
--- a/usr/bin/egup-single
+++ b/usr/bin/egup-single
@@ -23,7 +23,7 @@ fi
 set +e
 echo "(Updating Git tags file.)"
 [[ -f .egup.tags ]] && mv -f .egup.tags .egup.tags.old
-git show-ref -d --tags > .egup.tags || mv -fv .egup.tags.old .egup.tags || die "Failed writing .egup.tags in $(pwd)"
+( git show-ref -d --tags > .egup.tags || mv -fv .egup.tags.old .egup.tags ) || die "Failed writing .egup.tags in $(pwd)"
 rm -f .egup.tags.old
 set -e
 echo "(Done updating Git tags file.)"
