blah

diff --git a/usr/bin/egup-single b/usr/bin/egup-single
--- a/usr/bin/egup-single
+++ b/usr/bin/egup-single
@@ -21,7 +21,7 @@ if [[ -f .egup.git-native-excludes ]]; then
 fi
 
 # Back up the .gitignore in preparation for the next step
-git add .gitignore
+git add .gitignore || true # It's ok if this fails — it probably means there is no .gitignore
 git commit -m "Update Ember tree" || true #It's ok if this fails — it probably means there is nothing to commit
 
 if [[ "$(readlink -f .git/info/exclude)" == "$(readlink -f "$GIT_DIR"/info/exclude)" ]]; then
