blah

diff --git a/usr/bin/egup b/usr/bin/egup
--- a/usr/bin/egup
+++ b/usr/bin/egup
@@ -5,8 +5,9 @@ source ember_bash_setup &> /dev/null
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 #set -x
 
+egupCmd="egup"
 if [[ "$1" == "--offline" ]]; then
-    offline="true"
+    egupCmd="eogup"
     shift
 fi
 
@@ -23,15 +24,15 @@ EmberLibrary="$(crystallize-getconf EmberLibrary)"
         repoman manifest || warn "Repoman manifest failed!"
     )
     findemberlibraryfolders() {
-        find . -maxdepth 1 -not -name '\.*' -name "ember-library-[0-9]" -type d -print0 | xargs -i{} -0 -P 3 sh -c 'egup-single "$1"' -- '{}' \;
+        find . -maxdepth 1 -not -name '\.*' -name "ember-library-[0-9]" -type d -print0 | xargs -i{} -0 -P 3 sh -c "$egupCmd"'-single "$1"' -- '{}' \;
     }
     findemberfolders() {
-        find . -maxdepth 1 -not -name '\.*' -type d -print0 | xargs -i{} -0 -P 15 sh -c 'egup-single "$1"' -- '{}' \;
+        find . -maxdepth 1 -not -name '\.*' -type d -print0 | xargs -i{} -0 -P 15 sh -c "$egupCmd"'-single "$1"' -- '{}' \;
     }
     (
         (
             cd Futuramerlin\ Projects/Data/Crystal\ Index || error-notify "Could not open crystal index directory!"
-            egup-single . || error-notify "Could not egup-single $(pwd)!"
+            "$egupCmd"-single . || error-notify "Could not $egupCmd-single $(pwd)!"
         )
         cd Ember || error-notify "Could not open Ember directory!"
         (
@@ -44,10 +45,10 @@ EmberLibrary="$(crystallize-getconf EmberLibrary)"
         cd Ember\ satellite\ projects || error-notify "Could not open Ember satellite projects directory!"
         findemberfolders || error-notify "Error running satellite projects update!"
     )
-    egup-single Ember || error-notify "Could not egup-single $(pwd)!"
-    egup-single Ember\ satellite\ projects/wreathe-overlays-redist || warn "Note: failed updating redistributed overlays; this is normal if you only have a partial clone of the Ember tree"
-    egup-single Ember\ satellite\ projects || warn "Note: failed updating satellite projects meta-repository; this is normal if you only have a partial clone of the Ember tree"
+    "$egupCmd"-single Ember || error-notify "Could not $egupCmd-single $(pwd)!"
+    "$egupCmd"-single Ember\ satellite\ projects/wreathe-overlays-redist || warn "Note: failed updating redistributed overlays; this is normal if you only have a partial clone of the Ember tree"
+    "$egupCmd"-single Ember\ satellite\ projects || warn "Note: failed updating satellite projects meta-repository; this is normal if you only have a partial clone of the Ember tree"
 )
-egup-single "$EmberLibrary" || warn "Note: failed updating Ember meta-repository; this is normal if you only have a partial clone of the Ember tree"
+"$egupCmd"-single "$EmberLibrary" || warn "Note: failed updating Ember meta-repository; this is normal if you only have a partial clone of the Ember tree"
 printf "\033c"
 echo "Done updating."
