Update Ember tree

diff --git a/usr/bin/egup b/usr/bin/egup
--- a/usr/bin/egup
+++ b/usr/bin/egup
@@ -3,7 +3,7 @@
 source ember_bash_setup &> /dev/null
 
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
-set -x
+# set -x
 
 egupCmd="egup"
 if [[ "$1" == "--offline" ]]; then
@@ -11,77 +11,49 @@ if [[ "$1" == "--offline" ]]; then
     shift
 fi
 
-ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
 rubberfs save || die "Error running rubberfs save!"
-ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
 EmberLibrary="$(crystallize-getconf EmberLibrary)"
 (
     cd "$EmberLibrary" || error-notify "Could not open Ember Library directory!"
     (
         cd Ember\ satellite\ projects/compiz-reloaded-overlay || error-notify "Could not open compiz-reloaded-overlay directory!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        repoman manifest || warn "Repoman manifest failed!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    )
+                repoman manifest || warn "Repoman manifest failed!"
+            )
     (
         cd Ember\ satellite\ projects/wreathe-bootstrap/usr/local/portage || error-notify "Could not open wreathe-bootstrap directory!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        repoman manifest || warn "Repoman manifest failed!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    )
+                repoman manifest || warn "Repoman manifest failed!"
+            )
     (
         cd Ember\ satellite\ projects/wreathe-overlay || error-notify "Could not open wreathe-overlay directory!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        repoman manifest || warn "Repoman manifest failed!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    )
+                repoman manifest || warn "Repoman manifest failed!"
+            )
     (
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        elen
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        "$egupCmd"-single
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        elex
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    )
+                elen
+                "$egupCmd"-single
+                elex
+            )
     findemberlibraryfolders() {
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        find . -maxdepth 1 -not -name '\.*' -name "ember-library-[0-9]" -type d -print0 | xargs -i{} -0 -P 3 bash -c "source ember_bash_setup &> /dev/null; elen "$(basename "$1")"; $egupCmd"'-single; elex' -- '{}' \;
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    }
+                find . -maxdepth 1 -not -name '\.*' -name "ember-library-[0-9]" -type d -print0 | xargs -i{} -0 -P 3 bash -c "source ember_bash_setup &> /dev/null; elen "$(basename "$1")"; $egupCmd"'-single; elex' -- '{}' \;
+            }
     findemberfolders() {
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-      find . -maxdepth 1 -not -name '\.*' -type d -print0 | xargs -i{} -0 -P 5 bash -c "$egupCmd"'-single "$1"' -- '{}' \;
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    }
+              find . -maxdepth 1 -not -name '\.*' -type d -print0 | xargs -i{} -0 -P 5 bash -c "$egupCmd"'-single "$1"' -- '{}' \;
+            }
     (
         cd Ember || error-notify "Could not open Ember directory!"
         (
             cd ember-library || error-notify "Could not open Ember library directory!"
-            ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-            findemberlibraryfolders || error-notify "Error running Ember library folders update!"
-            ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        )
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        findemberfolders || error-notify "Error running Ember folders update!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    )
+                        findemberlibraryfolders || error-notify "Error running Ember library folders update!"
+                    )
+                findemberfolders || error-notify "Error running Ember folders update!"
+            )
     (
         cd Ember\ satellite\ projects || error-notify "Could not open Ember satellite projects directory!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-        findemberfolders || error-notify "Error running satellite projects update!"
-        ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
+                findemberfolders || error-notify "Error running satellite projects update!"
+            )
+        "$egupCmd"-single Ember || error-notify "Could not $egupCmd-single $(pwd)!"
+        "$egupCmd"-single Ember\ satellite\ projects/wreathe-overlays-redist || warn "Note: failed updating redistributed overlays; this is normal if you only have a partial clone of the Ember tree"
+        "$egupCmd"-single Ember\ satellite\ projects || warn "Note: failed updating satellite projects meta-repository; this is normal if you only have a partial clone of the Ember tree"
     )
-    ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    "$egupCmd"-single Ember || error-notify "Could not $egupCmd-single $(pwd)!"
-    ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    "$egupCmd"-single Ember\ satellite\ projects/wreathe-overlays-redist || warn "Note: failed updating redistributed overlays; this is normal if you only have a partial clone of the Ember tree"
-    ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-    "$egupCmd"-single Ember\ satellite\ projects || warn "Note: failed updating satellite projects meta-repository; this is normal if you only have a partial clone of the Ember tree"
-    ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
-)
-ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
 "$egupCmd"-single "$EmberLibrary" || warn "Note: failed updating Ember meta-repository; this is normal if you only have a partial clone of the Ember tree"
-ls -lsa /library/Ember/ember-library/ember-library-2/.egup.readme /library/.egup.readme /library/README.md /library/.egup.readme.bak || true
 printf "\033c"
 echo "Done updating."
