Update Ember tree

diff --git a/usr/bin/git-show-large-objects b/usr/bin/git-show-large-objects
--- a/usr/bin/git-show-large-objects
+++ b/usr/bin/git-show-large-objects
@@ -1,5 +1,9 @@
-#!/bin/bash
-#set -x 
+#!/usr/bin/env bash
+# shellcheck disable=SC1091
+source ember_bash_setup &> /dev/null
+# set -x
+
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 # Shows you the largest objects in your repo's pack file.
 # Written for osx.
@@ -11,7 +15,7 @@
 IFS=$'\n';
 
 # list all objects including their size, sort by size, take top 10
-objects=`git verify-pack -v .git/objects/pack/pack-*.idx | grep -v chain | sort -k3nr | head`
+objects=$(git verify-pack -v .git/objects/pack/pack-*.idx | grep -v chain | sort -k3nr | head)
 
 echo "All sizes are in kB. The pack column is the size of the object, compressed, inside the pack file."
 
